# Generated by Django 5.1.5 on 2025-02-22 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mhcapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
